name: arcpy_logging

channels:
  - conda-forge

dependencies:
  - pandas
  - pip
  - pytest
  - python=3.9
  - pip:
    - bump2version
    - furo
    - nbsphinx
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - tox
    - tox-conda
    - twine
